name: Build
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build-wasm:
    runs-on: ubuntu-latest
    env:
      CRATE_NAME: clue
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          override: true
          toolchain: nightly
          target: "wasm32-unknown-unknown"
      - name: Cache build
        uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
          target-directory: pkg
      - name: Build the binary
        run: |
          cargo install wasm-pack
          wasm-pack build --release --target web
          zip "$CRATE_NAME-pkg.zip" pkg/**/*
      - name: Upload the pkg folder
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CRATE_NAME }}-pkg.zip
          path: ${{ env.CRATE_NAME }}-pkg.zip

      - name: Publish in release
        uses: softprops/action-gh-release@v1
        with:
          files: |
          token: ${{ secrets.GITHUB_TOKEN }}
